In [39]:
import pandas as pd

In [40]:
measured_data = pd.read_csv(r"C:\Users\lkclu\Documents\GitHub\DTFS\configuration\202606_weekend_heatwave_results.csv")
measured_data.head()

,experiment_name,experiment_id,decision_number,control_timestamp,sensor_timestamp,elapsed_minutes_from_random_start,strategy_day,control_strategy,logical_flap_state,top_inside,...,OUTDOOR_AIR_TEMP_C,OUTDOOR_RELATIVE_HUMIDITY_PERCENT,SOLAR_RADIATION_VERTICAL_W_M2,INDOOR_TEMP_ANALOG_VOLTAGE_V,INDOOR_RH_ANALOG_VOLTAGE_V,OUTDOOR_TEMP_VOLTAGE_V,OUTDOOR_RH_VOLTAGE_V,PYRANOMETER_VOLTAGE_V,CONDENSATION_DETECTED,CONDENSATION_STATUS
0,Weekend_Heatwave_June2026,WHJ2026,1,2026-06-26T15:07:10,2026-06-26T13:07:01.725Z,-1012.82,WAITING,SAFE_WAITING,ALL_CLOSED,CLOSED,...,38.72,21.55,501.42,6.097,4.501,6.872,2.155,3.582,0.0,dry
1,Weekend_Heatwave_June2026,WHJ2026,2,2026-06-26T15:17:10,2026-06-26T13:17:08.712Z,-1002.82,WAITING,SAFE_WAITING,ALL_CLOSED,CLOSED,...,39.25,21.03,487.54,6.108,4.503,6.925,2.103,3.482,0.0,dry
2,Weekend_Heatwave_June2026,WHJ2026,3,2026-06-26T15:27:10,2026-06-26T13:27:08.760Z,-992.82,WAITING,SAFE_WAITING,ALL_CLOSED,CLOSED,...,38.98,20.90,490.23,6.106,4.495,6.898,2.090,3.502,0.0,dry
3,Weekend_Heatwave_June2026,WHJ2026,4,2026-06-26T15:37:10,2026-06-26T13:37:08.797Z,-982.82,WAITING,SAFE_WAITING,ALL_CLOSED,CLOSED,...,39.57,20.45,486.04,6.140,4.518,6.957,2.045,3.472,0.0,dry
4,Weekend_Heatwave_June2026,WHJ2026,5,2026-06-26T15:47:10,2026-06-26T13:47:08.889Z,-972.82,WAITING,SAFE_WAITING,ALL_CLOSED,CLOSED,...,39.27,21.19,517.08,6.156,4.528,6.927,2.119,3.693,0.0,dry

In [41]:
measured_data.control_timestamp

0      2026-06-26T15:07:10
1      2026-06-26T15:17:10
2      2026-06-26T15:27:10
3      2026-06-26T15:37:10
4      2026-06-26T15:47:10
              ...
385    2026-06-29T07:28:55
386    2026-06-29T07:38:55
387    2026-06-29T07:48:55
388    2026-06-29T07:58:55
389    2026-06-29T08:09:04
Name: control_timestamp, Length: 390, dtype: object

In [42]:
measured_data.columns.tolist()

['experiment_name',
 'experiment_id',
 'decision_number',
 'control_timestamp',
 'sensor_timestamp',
 'elapsed_minutes_from_random_start',
 'strategy_day',
 'control_strategy',
 'logical_flap_state',
 'top_inside',
 'top_outside',
 'bottom_inside',
 'bottom_outside',
 'command_sent',
 'decision_reason',
 'is_daytime',
 'temp_difference_black_globe_minus_outdoor_C',
 'radiation_above_threshold',
 'black_globe_hotter_than_outdoor',
 'radiation_threshold_W_m2',
 'temp_difference_threshold_C',
 'PCM_OC25_TEMP_C',
 'PCM_OC17_TEMP_C',
 'TOP_INBOUND_AIR_TEMP_1_C',
 'TOP_INBOUND_AIR_TEMP_2_C',
 'TOP_OUTBOUND_AIR_TEMP_1_C',
 'TOP_OUTBOUND_AIR_TEMP_2_C',
 'BOTTOM_INBOUND_AIR_TEMP_1_C',
 'BOTTOM_INBOUND_AIR_TEMP_2_C',
 'BOTTOM_OUTBOUND_AIR_TEMP_1_C',
 'BOTTOM_OUTBOUND_AIR_TEMP_2_C',
 'REFERENCE_AIR_TEMP_RTD_C',
 'TROMBE_WALL_SURFACE_TEMP_C',
 'CEILING_SURFACE_TEMP_C',
 'LEFT_WALL_SURFACE_TEMP_C',
 'RIGHT_WALL_SURFACE_TEMP_C',
 'REAR_WALL_SURFACE_TEMP_C',
 'FLOOR_SURFACE_TEMP_C',
 'BLACK_GLOBE_TEMP_C',
 'INDOOR_AIR_TEMP_ANALOG_C',
 'INDOOR_RELATIVE_HUMIDITY_ANALOG_PERCENT',
 'OUTDOOR_AIR_TEMP_C',
 'OUTDOOR_RELATIVE_HUMIDITY_PERCENT',
 'SOLAR_RADIATION_VERTICAL_W_M2',
 'INDOOR_TEMP_ANALOG_VOLTAGE_V',
 'INDOOR_RH_ANALOG_VOLTAGE_V',
 'OUTDOOR_TEMP_VOLTAGE_V',
 'OUTDOOR_RH_VOLTAGE_V',
 'PYRANOMETER_VOLTAGE_V',
 'CONDENSATION_DETECTED',
 'CONDENSATION_STATUS']

In [43]:
set(measured_data["logical_flap_state"].tolist())

{'ALL_CLOSED',
 'ALL_OPEN',
 'OUTBOUND_CLOSED_INBOUND_OPEN',
 'OUTBOUND_OPEN_INBOUND_CLOSED'}

In [44]:
#Dry bulb temperature, Total radiation on surface, Beam radiation on surface, Angle of incidence on surface, Sun zenith angle, Sun azimuth angle, Relative humidity, Wind speed, Effective sky temperature, Ground reflectance, Flap State Code

flap_state_map = {
    'ALL_CLOSED' : 0,
    'ALL_OPEN' : 2,
    'OUTBOUND_CLOSED_INBOUND_OPEN': 1,
    'OUTBOUND_OPEN_INBOUND_CLOSED': -1
}

prepared_data = pd.DataFrame()

prepared_data["Dry bulb temperature"] = measured_data["OUTDOOR_AIR_TEMP_C"]
prepared_data["Total radiation on surface"] = measured_data["SOLAR_RADIATION_VERTICAL_W_M2"]
prepared_data["Beam radiation on surface"] = measured_data["SOLAR_RADIATION_VERTICAL_W_M2"]
prepared_data["Angle of incidence on surface"] = 90
prepared_data["Sun zenith angle"] = 89
prepared_data["Sun azimuth angle"] = 180
prepared_data["Relative humidity"] = measured_data["OUTDOOR_RELATIVE_HUMIDITY_PERCENT"]
prepared_data["Wind speed"] = 0
prepared_data["Effective sky temperature"] = measured_data["OUTDOOR_AIR_TEMP_C"]
prepared_data["Ground reflectance"] = 0.2
prepared_data["Flap State Code"] = measured_data["logical_flap_state"].map(flap_state_map)
prepared_data["Indoor Air Temp"] = measured_data["INDOOR_AIR_TEMP_ANALOG_C"]
prepared_data['Outlet Air Temperature'] = measured_data['TOP_INBOUND_AIR_TEMP_1_C']
prepared_data['Wall Temperature'] = measured_data['PCM_OC25_TEMP_C']

In [45]:
prepared_data.head()

,Dry bulb temperature,Total radiation on surface,Beam radiation on surface,Angle of incidence on surface,Sun zenith angle,Sun azimuth angle,Relative humidity,Wind speed,Effective sky temperature,Ground reflectance,Flap State Code,Indoor Air Temp,Outlet Air Temperature,Wall Temperature
0,38.72,501.42,501.42,90,89,180,21.55,0,38.72,0.2,0,30.97,28.251,23.529
1,39.25,487.54,487.54,90,89,180,21.03,0,39.25,0.2,0,31.08,28.363,23.579
2,38.98,490.23,490.23,90,89,180,20.90,0,38.98,0.2,0,31.06,28.458,23.631
3,39.57,486.04,486.04,90,89,180,20.45,0,39.57,0.2,0,31.40,28.549,23.680
4,39.27,517.08,517.08,90,89,180,21.19,0,39.27,0.2,0,31.56,28.644,23.733

In [46]:
# Write header manually (comma + space separated), then data (tab separated)
with open(r"configuration\prepared_data.txt", "w") as f:
    f.write(", ".join(prepared_data.columns) + "\n")
    prepared_data.to_csv(f, sep="\t", header=False, index=False, lineterminator="\n")